# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'FlickerSample' do
pod 'AFNetworking', :head
pod 'SVProgressHUD', :head
pod 'FSImageViewer_image_resize'
end

target 'FlickerSampleTests' do

end

